const colors = {
  white: '#FFFFFF',
  backgroundColorBody: '#E5E5E5',
  backgroundColorModal: '#161C2D',
  backgroundColorButton: '#335EEA',
  colorTextLinkNormal: '#506690',
  colorTextLinkActive: '#335EEA',
  colorTextResultsFounded: '#869AB8',
  colorTextTitleBlog: '#161B2D',
  colorTextDescriptionBlog: '#6B7C93',
  backgroundColorBadgeGreen: '#42BA96',
  backgroundColorBadgeRed: '#DF4759',
  backgroundColorBadgeYellow: '#F2C94C',
  colorTextCopyright: '#000000',
  colorBorderButtonLoadMore: '#D9E2EF',
  colorLineSeparate: '#F3F7FB',
  colorEyeIcon: '#D2DDEC',
  colorDescriptionSign: '#6E84A3',
  colorUhOh: '#12263F',
  borderBottomHeader: '#E8E8E8',
  colorButtonClose: '#B1C2D9',
  colorButtonCloseHover: '#f2f2f2',
  colorHeaderH3: '#1766DC',
  colorShowOverlay: '#161c2dd4',
};

export default colors;